pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        maven {
            name = "legacy-fabric"
            url = "https://repo.legacyfabric.net/repository/legacyfabric/"
        }
        gradlePluginPortal()
    }
}

include "Drivers_Generic"
include "Drivers_v1_8"
include "Drivers_v1_12"
include "Drivers_v1_13"
include "Drivers_v1_16"
//--
include "Blackbox"
include "Supervisor"