pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        maven {
            name = "legacy-fabric"
            url = "https://maven.legacyfabric.net/"
        }
        maven {
            name = "jitpack"
            url = "https://jitpack.io/"
        }
        gradlePluginPortal()
    }
}

include "Drivers_Generic"
include "Drivers_v1_8"
include "Drivers_v1_12"
include "Drivers_v1_13"
include "Drivers_v1_14"
include "Drivers_v1_15"
include "Drivers_v1_16"
include "Drivers_v1_17"
include "Drivers_v1_19"
include "Drivers_v1_19_1"
include "Drivers_v1_19_4"
include "Drivers_v1_20_1"
include "Drivers_v1_20_4"
include "Drivers_v1_20_6"
include "Drivers_v1_21"
include "Drivers_v1_21_2"
include "Drivers_v1_21_4"
//--
include "Blackbox"
include "Supervisor"
include "Toolbox"
include "Integrator"
