plugins {
    id "legacy-looming" version "1.7-SNAPSHOT" // Version must be the same as fabric-loom's
}

repositories {
    maven { url 'https://jitpack.io/' }
    maven { url = "https://maven.meteordev.org/releases" }
    maven { url = "https://maven.meteordev.org/snapshots" }
    exclusiveContent {
        forRepository { maven { url = "https://api.modrinth.com/maven" } }
        filter { includeGroup "maven.modrinth" }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:1.8.9"
    mappings legacy.yarn("1.8.9", 541)

    implementation project(":Blackbox")

    // Wurst
    modApi "com.github.VideoGameSmash12:Wurst7:master"
    // Meteor
    modApi "meteordevelopment:meteor-client:0.5.8-SNAPSHOT"
    // ReplayMod
    modApi "maven.modrinth:replaymod:1.14.4-2.6.15"
}