plugins {
    id "legacy-looming" version "1.8-SNAPSHOT" // Version must be the same as fabric-loom's
}

dependencies {
    minecraft "com.mojang:minecraft:1.8.9"
    mappings legacy.yarn("1.8.9", 541)

    implementation project(":Supervisor")

    modImplementation "net.legacyfabric.legacy-fabric-api:legacy-fabric-api:1.9.4+1.8.9"
}