package me.videogamesm12.w2k.blackbox.window.menu;

import me.videogamesm12.w2k.blackbox.util.JComponents;
import me.videogamesm12.w2k.kernel.util.VersionUtils;
import me.videogamesm12.w2k.supervisor.Configuration;
import me.videogamesm12.w2k.supervisor.Supervisor;

import javax.swing.*;
import java.util.function.Consumer;
import java.util.function.Supplier;

public class MitigationsMenu extends JMenu
{
    public MitigationsMenu()
    {
        super("Mitigations");

        // GLOBAL
        final Configuration config = Supervisor.getConfig();

        // RENDERING
        add(setupRenderingMenu(config));    // RENDER
        add(setupNetworkingMenu(config));   // NETWORK
        addSeparator();                     //--
        add(setupDrasticMenu());            // DRASTIC
    }

    private JMenu setupDrasticMenu()
    {
        final JMenu menu = new JMenu("Drastic");
        menu.setToolTipText("Drastic actions you can take if necessary.");

        menu.add(JComponents.createMenuItem("Crash",
                "Forces the client to crash within the next render tick.",
                () -> Supervisor.getInstance().getFlags().setSupposedToCrash(true)));
        //--
        menu.add(JComponents.createMenuItem("Disconnect",
                "Immediately disconnects you from the server.",
                () ->
                {
                    try
                    {
                        Supervisor.getInstance().disconnect();
                    }
                    catch (IllegalStateException | IllegalArgumentException ex)
                    {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }));
        //--
        menu.add(JComponents.createMenuItem("Close Screen",
                "Closes whatever screen is currently open in-game.",
                () -> Supervisor.getInstance().closeCurrentScreen()));
        //--
        menu.add(JComponents.createMenuItem("Shutdown",
                "Safely closes the game.",
                () -> Supervisor.getInstance().shutdownSafely()));
        //--
        menu.add(JComponents.createMenuItem("Shutdown (Forcefully)",
                "Forcefully closes the game whilst still running necessary shutdown hooks.",
                () -> Supervisor.getInstance().shutdownForcefully()));
        //--
        menu.add(JComponents.createMenuItem("Shutdown (Nuclear)",
                "Terminates the game process before running any necessary shutdown hooks.\nThis will cause problems, so you should only do this if all else has failed.",
                () -> Supervisor.getInstance().shutdownNuclear()));

        return menu;
    }

    private JMenu setupNetworkingMenu(Configuration config)
    {
        final JMenu menu = new JMenu("Network");
        menu.setToolTipText("Network-related mitigations");
        final Configuration.Network network = config.getNetworkSettings();

        menu.add(JComponents.createCheckboxMenuItem("Ignore entity spawning",
                "Ignores packets for spawning entities. This does not prevent players from spawning, as that is an entirely separate packet.",
                network::isIgnoringEntitySpawns,
                network::setIgnoringEntitySpawns));
        //--
        menu.add(JComponents.createCheckboxMenuItem("Ignore explosions",
                "Ignores packets for spawning explosions. This does not prevent the block updates caused by explosions.",
                network::isIgnoringExplosions,
                network::setIgnoringExplosions));
        //--
        // Light update packets were introduced in 1.16, so this mitigation doesn't work on anything older than that
        if (VersionUtils.isNewerThanOrRunning("1.16.5"))
        {
            menu.add(JComponents.createCheckboxMenuItem("Ignore light updates",
                    "Ignores packets for light updates. Combats a known client lag exploit related to this.",
                    network::isIgnoringLightUpdates,
                    network::setIgnoringLightUpdates));
        }
        //--
        menu.add(JComponents.createCheckboxMenuItem("Ignore particle spawning",
                "Ignores packets for particle spawning. This does NOT affect particles generated by area effect clouds.",
                network::isIgnoringParticleSpawns,
                network::setIgnoringParticleSpawns));
        //--
        menu.add(JComponents.createCheckboxMenuItem("Ignore map updates",
                "Ignores packets for map data updates.\nUseful for preventing memory exhaustion exploits related to it.",
                network::isIgnoringMapUpdates,
                network::setIgnoringMapUpdates));

        return menu;
    }

    private JMenu setupRenderingMenu(Configuration config)
    {
        final JMenu menu = new JMenu("Render");
        menu.setToolTipText("Rendering-related mitigations");
        final Configuration.Rendering rendering = config.getRenderingSettings();

        menu.add(JComponents.createCheckboxMenuItem("Disable rendering completely",
                "Entirely disables any and all rendering for the game.",
                rendering::isGameRenderingDisabled,
                rendering::setGameRenderingDisabled));

        menu.add(JComponents.createCheckboxMenuItem("Disable world rendering",
                "Prevents the game from rendering the world itself.\nThis can create some pretty wacky visual effects.",
                rendering::isWorldRenderingDisabled,
                rendering::setWorldRenderingDisabled));

        menu.add(JComponents.createCheckboxMenuItem("Disable weather rendering",
                "Prevents the game from rendering the weather.\nHelpful for weaker hardware or in case the particles cause noticeable FPS drops.",
                rendering::isWeatherRenderingDisabled,
                rendering::setWeatherRenderingDisabled));

        menu.add(JComponents.createCheckboxMenuItem("Disable entity rendering",
                "Prevents the game from rendering entities.",
                rendering::isEntityRenderingDisabled,
                rendering::setEntityRenderingDisabled));

        menu.add(JComponents.createCheckboxMenuItem("Disable tile entity rendering",
                "Prevents the game from rendering tile entities (e.g. chests, shulker boxes, skulls, signs, etc).",
                rendering::isTileEntityRenderingDisabled,
                rendering::setTileEntityRenderingDisabled));

        return menu;
    }
}
