ext {
    remap = true
}

repositories {
    maven { url "https://jitpack.io/" }
}

dependencies {
    minecraft "com.mojang:minecraft:1.20.1"
    mappings "net.fabricmc:yarn:1.20.1+build.10:v2"

    implementation project(":Supervisor")
    implementation project(":Toolbox")
    implementation "net.kyori:adventure-api:4.17.0"
}