plugins {
    id "legacy-looming" version "1.7-SNAPSHOT" // Version must be the same as fabric-loom's
}

repositories {
    maven { url "https://jitpack.io/" }
}

dependencies {
    minecraft "com.mojang:minecraft:1.8.9"
    mappings legacy.yarn("1.8.9", 541)

    implementation project(":Supervisor")
    implementation "net.kyori:adventure-api:4.17.0"

    include compileOnly("com.formdev:flatlaf:3.0")
    include compileOnly("com.formdev:flatlaf-intellij-themes:3.0")
    include compileOnly("org.netbeans.modules:org-netbeans-swing-laf-dark:RELEASE130")
}